### ISSUE TITLE
Website Implementation - File Structure and Code Base

### ISSUE THREAD

**Issue by arpit2671991** [arpit2671991/LINUX#3]
# Website Implementation Plan

## File Structure
```
website/
├── assets/
│   ├── css/
│   │   ├── style.css
│   │   ├── animations.css
│   │   └── responsive.css
│   ├── js/
│   │   ├── main.js
│   │   ├── animations.js
│   │   └── form-validation.js
│   ├── images/
│   │   ├── hero/
│   │   ├── services/
│   │   └── icons/
│   └── fonts/
├── index.html
├── services.html
├── about.html
├── contact.html
└── academy.html
```

### Base HTML Template
```html name=base-template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>IT Solutions & Academy</title>
    <link rel="stylesheet" href="assets/css/style.css">
    <link rel="stylesheet" href="assets/css/animations.css">
    <link rel="stylesheet" href="assets/css/responsive.css">
    <!-- Add Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <!-- Add Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
</head>
<body>
    <!-- Navigation -->
    <nav class="navbar">
        <div class="container">
            <div class="logo">
                <a href="index.html">IT Solutions</a>
            </div>
            <ul class="nav-links">
                <li><a href="index.html">Home</a></li>
                <li><a href="services.html">Services</a></li>
                <li><a href="about.html">About</a></li>
                <li><a href="academy.html">Academy</a></li>
                <li><a href="contact.html" class="cta-button">Contact</a></li>
            </ul>
            <div class="mobile-menu">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>
    </nav>

    <!-- Content goes here -->

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="footer-content">
                <div class="footer-section">
                    <h3>Contact Us</h3>
                    <p>Email: info@itsolutions.com</p>
                    <p>Phone: +1 234 567 890</p>
                </div>
                <div class="footer-section">
                    <h3>Quick Links</h3>
                    <ul>
                        <li><a href="services.html">Services</a></li>
                        <li><a href="academy.html">Academy</a></li>
                        <li><a href="about.html">About Us</a></li>
                    </ul>
                </div>
                <div class="footer-section">
                    <h3>Follow Us</h3>
                    <div class="social-links">
                        <a href="#"><i class="fab fa-linkedin"></i></a>
                        <a href="#"><i class="fab fa-twitter"></i></a>
                        <a href="#"><i class="fab fa-facebook"></i></a>
                    </div>
                </div>
            </div>
            <div class="footer-bottom">
                <p>&copy; 2025 IT Solutions. All rights reserved.</p>
            </div>
        </div>
    </footer>

    <!-- Scripts -->
    <script src="assets/js/main.js"></script>
    <script src="assets/js/animations.js"></script>
</body>
</html>
```

### Core CSS Styles
```css name=style.css
/* Base Styles */
:root {
    --primary-color: #2563eb;
    --secondary-color: #1e40af;
    --text-color: #1f2937;
    --light-text: #6b7280;
    --background: #ffffff;
    --light-background: #f3f4f6;
    --transition: all 0.3s ease;
}

* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

body {
    font-family: 'Poppins', sans-serif;
    line-height: 1.6;
    color: var(--text-color);
}

.container {
    max-width: 1200px;
    margin: 0 auto;
    padding: 0 20px;
}

/* Navigation */
.navbar {
    background: var(--background);
    box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    position: fixed;
    width: 100%;
    top: 0;
    z-index: 1000;
}

.navbar .container {
    display: flex;
    justify-content: space-between;
    align-items: center;
    height: 80px;
}

.nav-links {
    display: flex;
    gap: 2rem;
    list-style: none;
}

.nav-links a {
    text-decoration: none;
    color: var(--text-color);
    font-weight: 500;
    transition: var(--transition);
}

.nav-links a:hover {
    color: var(--primary-color);
}

.cta-button {
    background: var(--primary-color);
    color: white !important;
    padding: 0.5rem 1.5rem;
    border-radius: 5px;
    transition: var(--transition);
}

.cta-button:hover {
    background: var(--secondary-color);
}

/* Hero Section */
.hero {
    height: 100vh;
    background-size: cover;
    background-position: center;
    display: flex;
    align-items: center;
    text-align: center;
    position: relative;
    margin-top: -80px;
}

.hero::before {
    content: '';
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: rgba(0,0,0,0.5);
}

.hero-content {
    position: relative;
    z-index: 1;
    color: white;
    max-width: 800px;
    margin: 0 auto;
    padding: 20px;
}

/* Service Cards */
.service-card {
    background: var(--background);
    border-radius: 10px;
    padding: 2rem;
    box-shadow: 0 4px 6px rgba(0,0,0,0.1);
    transition: var(--transition);
}

.service-card:hover {
    transform: translateY(-5px);
    box-shadow: 0 8px 12px rgba(0,0,0,0.15);
}

/* Testimonials */
.testimonial-slider {
    background: var(--light-background);
    padding: 4rem 0;
}

.testimonial-card {
    background: var(--background);
    padding: 2rem;
    border-radius: 10px;
    margin: 1rem;
    box-shadow: 0 2px 4px rgba(0,0,0,0.1);
}

/* Forms */
.contact-form {
    max-width: 600px;
    margin: 0 auto;
}

.form-group {
    margin-bottom: 1.5rem;
}

.form-control {
    width: 100%;
    padding: 0.75rem;
    border: 1px solid #ddd;
    border-radius: 5px;
    font-family: inherit;
}

/* Footer */
footer {
    background: var(--text-color);
    color: white;
    padding: 4rem 0 2rem;
}

.footer-content {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
    gap: 2rem;
}

.social-links {
    display: flex;
    gap: 1rem;
}

.social-links a {
    color: white;
    font-size: 1.5rem;
}
```

### Animations CSS
```css name=animations.css
/* Fade In Animation */
@keyframes fadeIn {
    from {
        opacity: 0;
        transform: translateY(20px);
    }
    to {
        opacity: 1;
        transform: translateY(0);
    }
}

.fade-in {
    animation: fadeIn 1s ease forwards;
}

/* Service Card Hover Effects */
.service-card {
    transition: transform 0.3s ease, box-shadow 0.3s ease;
}

.service-card:hover {
    transform: translateY(-5px);
    box-shadow: 0 8px 16px rgba(0,0,0,0.1);
}

/* Button Hover Animation */
.animated-button {
    position: relative;
    overflow: hidden;
}

.animated-button::after {
    content: '';
    position: absolute;
    top: 50%;
    left: 50%;
    width: 0;
    height: 0;
    background: rgba(255,255,255,0.2);
    border-radius: 50%;
    transform: translate(-50%, -50%);
    transition: width 0.6s ease, height 0.6s ease;
}

.animated-button:hover::after {
    width: 300px;
    height: 300px;
}

/* Scroll Reveal Animation */
.reveal {
    opacity: 0;
    transform: translateY(30px);
    transition: opacity 0.6s ease, transform 0.6s ease;
}

.reveal.active {
    opacity: 1;
    transform: translateY(0);
}

/* Counter Animation */
@keyframes countUp {
    from {
        transform: translateY(20px);
        opacity: 0;
    }
    to {
        transform: translateY(0);
        opacity: 1;
    }
}

.counter {
    animation: countUp 1s ease forwards;
}
```

### Core JavaScript
```javascript name=main.js
// Mobile Menu Toggle
document.addEventListener('DOMContentLoaded', () => {
    const mobileMenu = document.querySelector('.mobile-menu');
    const navLinks = document.querySelector('.nav-links');

    mobileMenu.addEventListener('click', () => {
        mobileMenu.classList.toggle('active');
        navLinks.classList.toggle('active');
    });

    // Scroll Reveal
    const revealElements = document.querySelectorAll('.reveal');
    
    const revealOnScroll = () => {
        revealElements.forEach(element => {
            const elementTop = element.getBoundingClientRect().top;
            const windowHeight = window.innerHeight;
            
            if (elementTop < windowHeight - 100) {
                element.classList.add('active');
            }
        });
    };

    window.addEventListener('scroll', revealOnScroll);
    revealOnScroll();

    // Counter Animation
    const counters = document.querySelectorAll('.counter');
    
    counters.forEach(counter => {
        const target = parseInt(counter.getAttribute('data-target'));
        const duration = 2000; // 2 seconds
        const step = target / (duration / 16); // 60fps
        let current = 0;
        
        const updateCounter = () => {
            current += step;
            counter.textContent = Math.round(current);
            
            if (current < target) {
                requestAnimationFrame(updateCounter);
            } else {
                counter.textContent = target;
            }
        };
        
        updateCounter();
    });

    // Form Validation
    const forms = document.querySelectorAll('form');
    
    forms.forEach(form => {
        form.addEventListener('submit', (e) => {
            e.preventDefault();
            
            const formData = new FormData(form);
            const data = Object.fromEntries(formData.entries());
            
            // Basic validation
            let isValid = true;
            const errors = {};
            
            for (const [key, value] of Object.entries(data)) {
                if (!value.trim()) {
                    isValid = false;
                    errors[key] = 'This field is required';
                }
            }
            
            if (data.email && !/\S+@\S+\.\S+/.test(data.email)) {
                isValid = false;
                errors.email = 'Please enter a valid email address';
            }
            
            if (isValid) {
                // Submit form
                console.log('Form submitted:', data);
                form.reset();
                showNotification('Form submitted successfully!', 'success');
            } else {
                showFormErrors(form, errors);
            }
        });
    });
});

// Testimonial Slider
class TestimonialSlider {
    constructor(element) {
        this.element = element;
        this.slides = element.querySelectorAll('.testimonial-slide');
        this.currentSlide = 0;
        this.init();
    }

    init() {
        this.showSlide(this.currentSlide);
        this.setupControls();
        this.startAutoPlay();
    }

    showSlide(index) {
        this.slides.forEach(slide => slide.style.display = 'none');
        this.slides[index].style.display = 'block';
    }

    nextSlide() {
        this.currentSlide = (this.currentSlide + 1) % this.slides.length;
        this.showSlide(this.currentSlide);
    }

    setupControls() {
        const nextButton = document.createElement('button');
        nextButton.classList.add('slider-control', 'next');
        nextButton.innerHTML = '→';
        nextButton.addEventListener('click', () => this.nextSlide());
        this.element.appendChild(nextButton);
    }

    startAutoPlay() {
        setInterval(() => this.nextSlide(), 5000);
    }
}

// Initialize slider
const slider = document.querySelector('.testimonial-slider');
if (slider) {
    new TestimonialSlider(slider);
}
```

## Next Steps for Implementation

1. Create the individual HTML pages using the base template:
   - Homepage (index.html)
   - Services page (services.html)
   - About page (about.html)
   - Contact page (contact.html)
   - Academy page (academy.html)

2. Add page-specific content and styles

3. Implement additional features:
   - Live chat widget integration
   - Course enrollment system
   - Payment gateway integration
   - Analytics tracking

4. Testing:
   - Cross-browser compatibility
   - Mobile responsiveness
   - Performance optimization
   - Form validation
   - Security measures

Would you like me to provide the implementation for any specific page or feature?
